{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.PaymentAccountFormField.FieldId exposing (FieldId(..), decodeFieldId, defaultFieldId, encodeFieldId, fieldNumbersFieldId)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs FieldId, decodeFieldId, defaultFieldId, encodeFieldId, fieldNumbersFieldId

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `FieldId`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersFieldId : FieldId -> Int
fieldNumbersFieldId n_ =
    case n_ of
        ADDRESS ->
            0

        ACCEPTEDCOUNTRYCODES ->
            1

        ACCOUNTID ->
            2

        ACCOUNTNAME ->
            3

        ACCOUNTNR ->
            4

        ACCOUNTOWNER ->
            5

        ACCOUNTTYPE ->
            6

        ANSWER ->
            7

        BANKACCOUNTNAME ->
            8

        BANKACCOUNTNUMBER ->
            9

        BANKACCOUNTTYPE ->
            10

        BANKADDRESS ->
            11

        BANKBRANCH ->
            12

        BANKBRANCHCODE ->
            13

        BANKBRANCHNAME ->
            14

        BANKCODE ->
            15

        BANKCOUNTRYCODE ->
            16

        BANKID ->
            17

        BANKNAME ->
            18

        BANKSWIFTCODE ->
            19

        BENEFICIARYACCOUNTNR ->
            20

        BENEFICIARYADDRESS ->
            21

        BENEFICIARYCITY ->
            22

        BENEFICIARYNAME ->
            23

        BENEFICIARYPHONE ->
            24

        BIC ->
            25

        BRANCHID ->
            26

        CITY ->
            27

        CONTACT ->
            28

        COUNTRY ->
            29

        EMAIL ->
            30

        EMAILORMOBILENR ->
            31

        EXTRAINFO ->
            32

        HOLDERADDRESS ->
            33

        HOLDEREMAIL ->
            34

        HOLDERNAME ->
            35

        HOLDERTAXID ->
            36

        IBAN ->
            37

        IFSC ->
            38

        INTERMEDIARYADDRESS ->
            39

        INTERMEDIARYBRANCH ->
            40

        INTERMEDIARYCOUNTRYCODE ->
            41

        INTERMEDIARYNAME ->
            42

        INTERMEDIARYSWIFTCODE ->
            43

        MOBILENR ->
            44

        NATIONALACCOUNTID ->
            45

        PAYID ->
            46

        PIXKEY ->
            47

        POSTALADDRESS ->
            48

        PROMPTPAYID ->
            49

        QUESTION ->
            50

        REQUIREMENTS ->
            51

        SALT ->
            52

        SORTCODE ->
            53

        SPECIALINSTRUCTIONS ->
            54

        STATE ->
            55

        TRADECURRENCIES ->
            56

        USERNAME ->
            57

        EMAILORMOBILENRORUSERNAME ->
            58

        EMAILORMOBILENRORCASHTAG ->
            59

        FieldIdUnrecognized_ m_ ->
            m_


{-| Default for FieldId. Should only be used for 'required' decoders as an initial value.

-}
defaultFieldId : FieldId
defaultFieldId =
    ADDRESS


{-| Declares how to encode a `FieldId` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeFieldId : FieldId -> Protobuf.Encode.Encoder
encodeFieldId value =
    Protobuf.Encode.int32 <|
        case value of
            ADDRESS ->
                0

            ACCEPTEDCOUNTRYCODES ->
                1

            ACCOUNTID ->
                2

            ACCOUNTNAME ->
                3

            ACCOUNTNR ->
                4

            ACCOUNTOWNER ->
                5

            ACCOUNTTYPE ->
                6

            ANSWER ->
                7

            BANKACCOUNTNAME ->
                8

            BANKACCOUNTNUMBER ->
                9

            BANKACCOUNTTYPE ->
                10

            BANKADDRESS ->
                11

            BANKBRANCH ->
                12

            BANKBRANCHCODE ->
                13

            BANKBRANCHNAME ->
                14

            BANKCODE ->
                15

            BANKCOUNTRYCODE ->
                16

            BANKID ->
                17

            BANKNAME ->
                18

            BANKSWIFTCODE ->
                19

            BENEFICIARYACCOUNTNR ->
                20

            BENEFICIARYADDRESS ->
                21

            BENEFICIARYCITY ->
                22

            BENEFICIARYNAME ->
                23

            BENEFICIARYPHONE ->
                24

            BIC ->
                25

            BRANCHID ->
                26

            CITY ->
                27

            CONTACT ->
                28

            COUNTRY ->
                29

            EMAIL ->
                30

            EMAILORMOBILENR ->
                31

            EXTRAINFO ->
                32

            HOLDERADDRESS ->
                33

            HOLDEREMAIL ->
                34

            HOLDERNAME ->
                35

            HOLDERTAXID ->
                36

            IBAN ->
                37

            IFSC ->
                38

            INTERMEDIARYADDRESS ->
                39

            INTERMEDIARYBRANCH ->
                40

            INTERMEDIARYCOUNTRYCODE ->
                41

            INTERMEDIARYNAME ->
                42

            INTERMEDIARYSWIFTCODE ->
                43

            MOBILENR ->
                44

            NATIONALACCOUNTID ->
                45

            PAYID ->
                46

            PIXKEY ->
                47

            POSTALADDRESS ->
                48

            PROMPTPAYID ->
                49

            QUESTION ->
                50

            REQUIREMENTS ->
                51

            SALT ->
                52

            SORTCODE ->
                53

            SPECIALINSTRUCTIONS ->
                54

            STATE ->
                55

            TRADECURRENCIES ->
                56

            USERNAME ->
                57

            EMAILORMOBILENRORUSERNAME ->
                58

            EMAILORMOBILENRORCASHTAG ->
                59

            FieldIdUnrecognized_ i ->
                i


{-| Declares how to decode a `FieldId` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeFieldId : Protobuf.Decode.Decoder FieldId
decodeFieldId =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        ADDRESS

                    1 ->
                        ACCEPTEDCOUNTRYCODES

                    2 ->
                        ACCOUNTID

                    3 ->
                        ACCOUNTNAME

                    4 ->
                        ACCOUNTNR

                    5 ->
                        ACCOUNTOWNER

                    6 ->
                        ACCOUNTTYPE

                    7 ->
                        ANSWER

                    8 ->
                        BANKACCOUNTNAME

                    9 ->
                        BANKACCOUNTNUMBER

                    10 ->
                        BANKACCOUNTTYPE

                    11 ->
                        BANKADDRESS

                    12 ->
                        BANKBRANCH

                    13 ->
                        BANKBRANCHCODE

                    14 ->
                        BANKBRANCHNAME

                    15 ->
                        BANKCODE

                    16 ->
                        BANKCOUNTRYCODE

                    17 ->
                        BANKID

                    18 ->
                        BANKNAME

                    19 ->
                        BANKSWIFTCODE

                    20 ->
                        BENEFICIARYACCOUNTNR

                    21 ->
                        BENEFICIARYADDRESS

                    22 ->
                        BENEFICIARYCITY

                    23 ->
                        BENEFICIARYNAME

                    24 ->
                        BENEFICIARYPHONE

                    25 ->
                        BIC

                    26 ->
                        BRANCHID

                    27 ->
                        CITY

                    28 ->
                        CONTACT

                    29 ->
                        COUNTRY

                    30 ->
                        EMAIL

                    31 ->
                        EMAILORMOBILENR

                    32 ->
                        EXTRAINFO

                    33 ->
                        HOLDERADDRESS

                    34 ->
                        HOLDEREMAIL

                    35 ->
                        HOLDERNAME

                    36 ->
                        HOLDERTAXID

                    37 ->
                        IBAN

                    38 ->
                        IFSC

                    39 ->
                        INTERMEDIARYADDRESS

                    40 ->
                        INTERMEDIARYBRANCH

                    41 ->
                        INTERMEDIARYCOUNTRYCODE

                    42 ->
                        INTERMEDIARYNAME

                    43 ->
                        INTERMEDIARYSWIFTCODE

                    44 ->
                        MOBILENR

                    45 ->
                        NATIONALACCOUNTID

                    46 ->
                        PAYID

                    47 ->
                        PIXKEY

                    48 ->
                        POSTALADDRESS

                    49 ->
                        PROMPTPAYID

                    50 ->
                        QUESTION

                    51 ->
                        REQUIREMENTS

                    52 ->
                        SALT

                    53 ->
                        SORTCODE

                    54 ->
                        SPECIALINSTRUCTIONS

                    55 ->
                        STATE

                    56 ->
                        TRADECURRENCIES

                    57 ->
                        USERNAME

                    58 ->
                        EMAILORMOBILENRORUSERNAME

                    59 ->
                        EMAILORMOBILENRORCASHTAG

                    _ ->
                        FieldIdUnrecognized_ i
            )


{-| `FieldId` enumeration

-}
type FieldId
    = ADDRESS
    | ACCEPTEDCOUNTRYCODES
    | ACCOUNTID
    | ACCOUNTNAME
    | ACCOUNTNR
    | ACCOUNTOWNER
    | ACCOUNTTYPE
    | ANSWER
    | BANKACCOUNTNAME
    | BANKACCOUNTNUMBER
    | BANKACCOUNTTYPE
    | BANKADDRESS
    | BANKBRANCH
    | BANKBRANCHCODE
    | BANKBRANCHNAME
    | BANKCODE
    | BANKCOUNTRYCODE
    | BANKID
    | BANKNAME
    | BANKSWIFTCODE
    | BENEFICIARYACCOUNTNR
    | BENEFICIARYADDRESS
    | BENEFICIARYCITY
    | BENEFICIARYNAME
    | BENEFICIARYPHONE
    | BIC
    | BRANCHID
    | CITY
    | CONTACT
    | COUNTRY
    | EMAIL
    | EMAILORMOBILENR
    | EXTRAINFO
    | HOLDERADDRESS
    | HOLDEREMAIL
    | HOLDERNAME
    | HOLDERTAXID
    | IBAN
    | IFSC
    | INTERMEDIARYADDRESS
    | INTERMEDIARYBRANCH
    | INTERMEDIARYCOUNTRYCODE
    | INTERMEDIARYNAME
    | INTERMEDIARYSWIFTCODE
    | MOBILENR
    | NATIONALACCOUNTID
    | PAYID
    | PIXKEY
    | POSTALADDRESS
    | PROMPTPAYID
    | QUESTION
    | REQUIREMENTS
    | SALT
    | SORTCODE
    | SPECIALINSTRUCTIONS
    | STATE
    | TRADECURRENCIES
    | USERNAME
    | EMAILORMOBILENRORUSERNAME
    | EMAILORMOBILENRORCASHTAG
    | FieldIdUnrecognized_ Int
