{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.BankAccountPayload.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### NationalBankAccountPayload

### SameBankAccontPayload

### SpecificBanksAccountPayload

### AchTransferAccountPayload

### DomesticWireTransferAccountPayload

-}
type Message a0 a1 a2 a3 a4
    = NationalBankAccountPayload a0
    | SameBankAccontPayload a1
    | SpecificBanksAccountPayload a2
    | AchTransferAccountPayload a3
    | DomesticWireTransferAccountPayload a4
