{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.NetworkEnvelope.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### PreliminaryGetDataRequest

### GetDataResponse

### GetUpdatedDataRequest

### GetPeersRequest

### GetPeersResponse

### Ping

### Pong

### OfferAvailabilityRequest

### OfferAvailabilityResponse

### RefreshOfferMessage

### AddDataMessage

### RemoveDataMessage

### RemoveMailboxDataMessage

### CloseConnectionMessage

### PrefixedSealedAndSignedMessage

### PrivateNotificationMessage

### AddPersistableNetworkPayloadMessage

### AckMessage

### BundleOfEnvelopes

### GetInventoryRequest

### GetInventoryResponse

### SignOfferRequest

### SignOfferResponse

### InitTradeRequest

### InitMultisigRequest

### SignContractRequest

### SignContractResponse

### DepositRequest

### DepositResponse

### DepositsConfirmedMessage

### PaymentSentMessage

### PaymentReceivedMessage

### DisputeOpenedMessage

### DisputeClosedMessage

### ChatMessage

### MediatedPayoutTxSignatureMessage

### MediatedPayoutTxPublishedMessage

### FileTransferPart

-}
type Message a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36 a37
    = PreliminaryGetDataRequest a0
    | GetDataResponse a1
    | GetUpdatedDataRequest a2
    | GetPeersRequest a3
    | GetPeersResponse a4
    | Ping a5
    | Pong a6
    | OfferAvailabilityRequest a7
    | OfferAvailabilityResponse a8
    | RefreshOfferMessage a9
    | AddDataMessage a10
    | RemoveDataMessage a11
    | RemoveMailboxDataMessage a12
    | CloseConnectionMessage a13
    | PrefixedSealedAndSignedMessage a14
    | PrivateNotificationMessage a15
    | AddPersistableNetworkPayloadMessage a16
    | AckMessage a17
    | BundleOfEnvelopes a18
    | GetInventoryRequest a19
    | GetInventoryResponse a20
    | SignOfferRequest a21
    | SignOfferResponse a22
    | InitTradeRequest a23
    | InitMultisigRequest a24
    | SignContractRequest a25
    | SignContractResponse a26
    | DepositRequest a27
    | DepositResponse a28
    | DepositsConfirmedMessage a29
    | PaymentSentMessage a30
    | PaymentReceivedMessage a31
    | DisputeOpenedMessage a32
    | DisputeClosedMessage a33
    | ChatMessage a34
    | MediatedPayoutTxSignatureMessage a35
    | MediatedPayoutTxPublishedMessage a36
    | FileTransferPart a37
