{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.CountryBasedPaymentAccountPayload.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### BankAccountPayload

### CashDepositAccountPayload

### SepaAccountPayload

### WesternUnionAccountPayload

### SepaInstantAccountPayload

### F2fAccountPayload

### UpiAccountPayload

### PaytmAccountPayload

### IfscBasedAccountPayload

### NequiAccountPayload

### BizumAccountPayload

### PixAccountPayload

### SatispayAccountPayload

### StrikeAccountPayload

### TikkieAccountPayload

### TransferwiseUsdAccountPayload

### SwiftAccountPayload

-}
type Message a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16
    = BankAccountPayload a0
    | CashDepositAccountPayload a1
    | SepaAccountPayload a2
    | WesternUnionAccountPayload a3
    | SepaInstantAccountPayload a4
    | F2fAccountPayload a5
    | UpiAccountPayload a6
    | PaytmAccountPayload a7
    | IfscBasedAccountPayload a8
    | NequiAccountPayload a9
    | BizumAccountPayload a10
    | PixAccountPayload a11
    | SatispayAccountPayload a12
    | StrikeAccountPayload a13
    | TikkieAccountPayload a14
    | TransferwiseUsdAccountPayload a15
    | SwiftAccountPayload a16
