# NOTE: This project is using the Gitlab runner assigned from the Zoho-Responsive scheduler project
stages:
  - check-yarn
  - test
  - integration_test
  - deploy

install-yarn:
  stage: check-yarn
  image: node:21  # Or another Node version that works for your project
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn --version
  only:
    - master
  artifacts:
    # Cache Yarn and Node.js for reuse in other stages
    paths:
      - $HOME/.yarn
      - $HOME/.config/yarn
      - node_modules
    expire_in: 1h

test:
  stage: test
  image: node:21  # Ensure the same node version or compatible version
  dependencies:
    - install-yarn  # Use artifacts from install-yarn stage
  script:
    # Re-add the PATH to include yarn
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    # Ensure the correct working directory
    - cd $CI_PROJECT_DIR
    # Install project dependencies including Elm and Parcel
    - yarn install
    - npx elm make src/Main.elm --output=js/elm.js --optimize
    - npx elm-test 'src/**/Tests/Test*.elm'
    # Run Parcel build
    - yarn build

integration_test:
  stage: integration_test
  image: node:21  # Ensure the same node version or compatible version
  dependencies:
    - install-yarn  # Use artifacts from install-yarn stage
  script:
    # Re-add the PATH to include yarn
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    # Ensure the correct working directory
    - cd $CI_PROJECT_DIR
    # Install project dependencies including Elm and Parcel
    - yarn install
    # WARN: Haveno-Web-Zoho-Responsive has PATH variable set to PATH1
    - export PATH=./node_modules/.bin:$PATH
    - npx elm make src/Main.elm --output=js/elm.js --optimize 
    - yarn add elm-spec-runner
    - npx elm-spec --specRoot ./
    # Run Parcel build
    - yarn build
    
deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --update lftp
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - |
      lftp -d -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_SERVER:21098" << EOF
        # Delete all files in the target directory (but keep subdirectories)
        set sftp:connect-program 'ssh -a -x -s -l squastgr -p 21098 -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
        mirror --reverse --delete --only-newer ./dist /home/squastgr/haveno-web.squashpassion.com/public_html
        # Remove files while keeping subdirectories
        rm -rf /home/squastgr/haveno-web.squashpassion.com/public_html/* 
        # Mirror the new files
        mirror -R ./dist /home/squastgr/haveno-web.squashpassion.com/public_html
        quit
      EOF
  only:
    - master
  dependencies:
    - test
    - integration_test

