# NOTE: This project is using the Gitlab runner assigned from the Zoho-Responsive scheduler project
stages:
  - test
  - integration_test
  - deploy
  
test:
  stage: test
  script:
    - apt-get update -qy # Update package list (for Debian/Ubuntu-based runners)
    - apt-get install -qy nodejs yarn # Install Node.js and Yarn
    # Ensure the correct working directory
    - cd $CI_PROJECT_DIR
    # Install project dependencies including Elm and Parcel
    - yarn install
    - npx elm make src/Main.elm --output=js/elm.js --optimize
    - npx elm-test 'src/**/Tests/Test*.elm'
    # Run Parcel build
    - yarn build

integration_test:
  stage: integration_test
  script:
    - apt-get update -qy 
    - apt-get install -qy nodejs yarn
    # Ensure the correct working directory
    - cd $CI_PROJECT_DIR
    # Install project dependencies including Elm and Parcel
    - yarn install
    # WARN: Haveno-Web-Zoho-Responsive has PATH variable set to PATH1
    - export PATH=./node_modules/.bin:$PATH
    - npx elm make src/Main.elm --output=js/elm.js --optimize 
    - yarn add elm-spec-runner
    - npx elm-spec --specRoot ./
    # Run Parcel build
    - yarn build
    
deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --update lftp
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - lftp -d -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_SERVER:21098" -e "set sftp:connect-program 'ssh -a -x -s -l squastgr -p 21098 -oHostKeyAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'; mirror -R ./dist /home/squastgr/haveno-web.squashpassion.com/public_html; quit"

  only:
    - master
  dependencies:
    - test
    - integration_test