stages:
  - check-yarn

install-yarn:
  stage: check-yarn
  image: node:21  # Or another Node version that works for your project
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - yarn --version
    - yarn help
  only:
    - master
