{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.UrlConnection.OnlineStatus exposing (OnlineStatus(..), decodeOnlineStatus, defaultOnlineStatus, encodeOnlineStatus, fieldNumbersOnlineStatus)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs OnlineStatus, decodeOnlineStatus, defaultOnlineStatus, encodeOnlineStatus, fieldNumbersOnlineStatus

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `OnlineStatus`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersOnlineStatus : OnlineStatus -> Int
fieldNumbersOnlineStatus n_ =
    case n_ of
        UNKNOWN ->
            0

        ONLINE ->
            1

        OFFLINE ->
            2

        OnlineStatusUnrecognized_ m_ ->
            m_


{-| Default for OnlineStatus. Should only be used for 'required' decoders as an initial value.

-}
defaultOnlineStatus : OnlineStatus
defaultOnlineStatus =
    UNKNOWN


{-| Declares how to encode a `OnlineStatus` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeOnlineStatus : OnlineStatus -> Protobuf.Encode.Encoder
encodeOnlineStatus value =
    Protobuf.Encode.int32 <|
        case value of
            UNKNOWN ->
                0

            ONLINE ->
                1

            OFFLINE ->
                2

            OnlineStatusUnrecognized_ i ->
                i


{-| Declares how to decode a `OnlineStatus` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeOnlineStatus : Protobuf.Decode.Decoder OnlineStatus
decodeOnlineStatus =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        UNKNOWN

                    1 ->
                        ONLINE

                    2 ->
                        OFFLINE

                    _ ->
                        OnlineStatusUnrecognized_ i
            )


{-| `OnlineStatus` enumeration

-}
type OnlineStatus
    = UNKNOWN
    | ONLINE
    | OFFLINE
    | OnlineStatusUnrecognized_ Int
