{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.Trade.Phase exposing (Phase(..), decodePhase, defaultPhase, encodePhase, fieldNumbersPhase)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Phase, decodePhase, defaultPhase, encodePhase, fieldNumbersPhase

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Phase`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPhase : Phase -> Int
fieldNumbersPhase n_ =
    case n_ of
        PBERRORPHASE ->
            0

        INIT ->
            1

        DEPOSITREQUESTED ->
            2

        DEPOSITSPUBLISHED ->
            3

        DEPOSITSCONFIRMED ->
            4

        DEPOSITSUNLOCKED ->
            5

        PAYMENTSENT ->
            6

        PAYMENTRECEIVED ->
            7

        PhaseUnrecognized_ m_ ->
            m_


{-| Default for Phase. Should only be used for 'required' decoders as an initial value.

-}
defaultPhase : Phase
defaultPhase =
    PBERRORPHASE


{-| Declares how to encode a `Phase` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePhase : Phase -> Protobuf.Encode.Encoder
encodePhase value =
    Protobuf.Encode.int32 <|
        case value of
            PBERRORPHASE ->
                0

            INIT ->
                1

            DEPOSITREQUESTED ->
                2

            DEPOSITSPUBLISHED ->
                3

            DEPOSITSCONFIRMED ->
                4

            DEPOSITSUNLOCKED ->
                5

            PAYMENTSENT ->
                6

            PAYMENTRECEIVED ->
                7

            PhaseUnrecognized_ i ->
                i


{-| Declares how to decode a `Phase` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePhase : Protobuf.Decode.Decoder Phase
decodePhase =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PBERRORPHASE

                    1 ->
                        INIT

                    2 ->
                        DEPOSITREQUESTED

                    3 ->
                        DEPOSITSPUBLISHED

                    4 ->
                        DEPOSITSCONFIRMED

                    5 ->
                        DEPOSITSUNLOCKED

                    6 ->
                        PAYMENTSENT

                    7 ->
                        PAYMENTRECEIVED

                    _ ->
                        PhaseUnrecognized_ i
            )


{-| `Phase` enumeration

-}
type Phase
    = PBERRORPHASE
    | INIT
    | DEPOSITREQUESTED
    | DEPOSITSPUBLISHED
    | DEPOSITSCONFIRMED
    | DEPOSITSUNLOCKED
    | PAYMENTSENT
    | PAYMENTRECEIVED
    | PhaseUnrecognized_ Int
