{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.Tradable.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### OpenOffer

### SignedOffer

### BuyerAsMakerTrade

### BuyerAsTakerTrade

### SellerAsMakerTrade

### SellerAsTakerTrade

### ArbitratorTrade

-}
type Message a0 a1 a2 a3 a4 a5 a6
    = OpenOffer a0
    | SignedOffer a1
    | BuyerAsMakerTrade a2
    | BuyerAsTakerTrade a3
    | SellerAsMakerTrade a4
    | SellerAsTakerTrade a5
    | ArbitratorTrade a6
