{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.PaymentAccountPayload.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### AliPayAccountPayload

### ChaseQuickPayAccountPayload

### ZelleAccountPayload

### CountryBasedPaymentAccountPayload

### CryptoCurrencyAccountPayload

### FasterPaymentsAccountPayload

### InteracETransferAccountPayload

### OKPayAccountPayload

### PerfectMoneyAccountPayload

### SwishAccountPayload

### USPostalMoneyOrderAccountPayload

### UpholdAccountPayload

### CashAppAccountPayload

### MoneyBeamAccountPayload

### VenmoAccountPayload

### PopmoneyAccountPayload

### RevolutAccountPayload

### WeChatPayAccountPayload

### MoneyGramAccountPayload

### HalCashAccountPayload

### PromptPayAccountPayload

### AdvancedCashAccountPayload

### InstantCryptoCurrencyAccountPayload

### JapanBankAccountPayload

### TransferwiseAccountPayload

### AustraliaPayidPayload

### AmazonGiftCardAccountPayload

### PayByMailAccountPayload

### CapitualAccountPayload

### PayseraAccountPayload

### PaxumAccountPayload

### SwiftAccountPayload

### CelPayAccountPayload

### MoneseAccountPayload

### VerseAccountPayload

### CashAtAtmAccountPayload

### PaypalAccountPayload

-}
type Message a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20 a21 a22 a23 a24 a25 a26 a27 a28 a29 a30 a31 a32 a33 a34 a35 a36
    = AliPayAccountPayload a0
    | ChaseQuickPayAccountPayload a1
    | ZelleAccountPayload a2
    | CountryBasedPaymentAccountPayload a3
    | CryptoCurrencyAccountPayload a4
    | FasterPaymentsAccountPayload a5
    | InteracETransferAccountPayload a6
    | OKPayAccountPayload a7
    | PerfectMoneyAccountPayload a8
    | SwishAccountPayload a9
    | USPostalMoneyOrderAccountPayload a10
    | UpholdAccountPayload a11
    | CashAppAccountPayload a12
    | MoneyBeamAccountPayload a13
    | VenmoAccountPayload a14
    | PopmoneyAccountPayload a15
    | RevolutAccountPayload a16
    | WeChatPayAccountPayload a17
    | MoneyGramAccountPayload a18
    | HalCashAccountPayload a19
    | PromptPayAccountPayload a20
    | AdvancedCashAccountPayload a21
    | InstantCryptoCurrencyAccountPayload a22
    | JapanBankAccountPayload a23
    | TransferwiseAccountPayload a24
    | AustraliaPayidPayload a25
    | AmazonGiftCardAccountPayload a26
    | PayByMailAccountPayload a27
    | CapitualAccountPayload a28
    | PayseraAccountPayload a29
    | PaxumAccountPayload a30
    | SwiftAccountPayload a31
    | CelPayAccountPayload a32
    | MoneseAccountPayload a33
    | VerseAccountPayload a34
    | CashAtAtmAccountPayload a35
    | PaypalAccountPayload a36
