{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.GetTradeStatistics exposing (getTradeStatistics)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 GetTradeStatistics
/////////////////////////////////////////////////////////////////////////////////////////


@docs getTradeStatistics

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'GetTradeStatistics' sending a `GetTradeStatisticsRequest` to get back a `GetTradeStatisticsReply`.

-}
getTradeStatistics :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetTradeStatisticsRequest Proto.Io.Haveno.Protobuffer.GetTradeStatisticsReply
getTradeStatistics =
    Grpc.Internal.Rpc
        { service = "GetTradeStatistics"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetTradeStatistics"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetTradeStatisticsRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetTradeStatisticsReply
        }
