{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.GetVersion exposing (getVersion)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 Version
/////////////////////////////////////////////////////////////////////////////////////////


@docs getVersion

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'GetVersion' sending a `GetVersionRequest` to get back a `GetVersionReply`.

-}
getVersion : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetVersionRequest Proto.Io.Haveno.Protobuffer.GetVersionReply
getVersion =
    Grpc.Internal.Rpc
        { service = "GetVersion"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetVersion"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetVersionRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetVersionReply
        }
