{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.Help exposing (getMethodHelp)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 Help
/////////////////////////////////////////////////////////////////////////////////////////


@docs getMethodHelp

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'GetMethodHelp' sending a `GetMethodHelpRequest` to get back a `GetMethodHelpReply`.

-}
getMethodHelp :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetMethodHelpRequest Proto.Io.Haveno.Protobuffer.GetMethodHelpReply
getMethodHelp =
    Grpc.Internal.Rpc
        { service = "Help"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetMethodHelp"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetMethodHelpRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetMethodHelpReply
        }
