{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.MediationResultState exposing (MediationResultState(..), decodeMediationResultState, defaultMediationResultState, encodeMediationResultState, fieldNumbersMediationResultState)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs MediationResultState, decodeMediationResultState, defaultMediationResultState, encodeMediationResultState

@docs fieldNumbersMediationResultState

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `MediationResultState`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersMediationResultState : MediationResultState -> Int
fieldNumbersMediationResultState n_ =
    case n_ of
        PBERRORMEDIATIONRESULT ->
            0

        UNDEFINEDMEDIATIONRESULT ->
            1

        MEDIATIONRESULTACCEPTED ->
            2

        MEDIATIONRESULTREJECTED ->
            3

        SIGMSGSENT ->
            4

        SIGMSGARRIVED ->
            5

        SIGMSGINMAILBOX ->
            6

        SIGMSGSENDFAILED ->
            7

        RECEIVEDSIGMSG ->
            8

        PAYOUTTXPUBLISHED ->
            9

        PAYOUTTXPUBLISHEDMSGSENT ->
            10

        PAYOUTTXPUBLISHEDMSGARRIVED ->
            11

        PAYOUTTXPUBLISHEDMSGINMAILBOX ->
            12

        PAYOUTTXPUBLISHEDMSGSENDFAILED ->
            13

        RECEIVEDPAYOUTTXPUBLISHEDMSG ->
            14

        PAYOUTTXSEENINNETWORK ->
            15

        MediationResultStateUnrecognized_ m_ ->
            m_


{-| Default for MediationResultState. Should only be used for 'required' decoders as an initial value.

-}
defaultMediationResultState : MediationResultState
defaultMediationResultState =
    PBERRORMEDIATIONRESULT


{-| Declares how to encode a `MediationResultState` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeMediationResultState : MediationResultState -> Protobuf.Encode.Encoder
encodeMediationResultState value =
    Protobuf.Encode.int32 <|
        case value of
            PBERRORMEDIATIONRESULT ->
                0

            UNDEFINEDMEDIATIONRESULT ->
                1

            MEDIATIONRESULTACCEPTED ->
                2

            MEDIATIONRESULTREJECTED ->
                3

            SIGMSGSENT ->
                4

            SIGMSGARRIVED ->
                5

            SIGMSGINMAILBOX ->
                6

            SIGMSGSENDFAILED ->
                7

            RECEIVEDSIGMSG ->
                8

            PAYOUTTXPUBLISHED ->
                9

            PAYOUTTXPUBLISHEDMSGSENT ->
                10

            PAYOUTTXPUBLISHEDMSGARRIVED ->
                11

            PAYOUTTXPUBLISHEDMSGINMAILBOX ->
                12

            PAYOUTTXPUBLISHEDMSGSENDFAILED ->
                13

            RECEIVEDPAYOUTTXPUBLISHEDMSG ->
                14

            PAYOUTTXSEENINNETWORK ->
                15

            MediationResultStateUnrecognized_ i ->
                i


{-| Declares how to decode a `MediationResultState` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeMediationResultState : Protobuf.Decode.Decoder MediationResultState
decodeMediationResultState =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PBERRORMEDIATIONRESULT

                    1 ->
                        UNDEFINEDMEDIATIONRESULT

                    2 ->
                        MEDIATIONRESULTACCEPTED

                    3 ->
                        MEDIATIONRESULTREJECTED

                    4 ->
                        SIGMSGSENT

                    5 ->
                        SIGMSGARRIVED

                    6 ->
                        SIGMSGINMAILBOX

                    7 ->
                        SIGMSGSENDFAILED

                    8 ->
                        RECEIVEDSIGMSG

                    9 ->
                        PAYOUTTXPUBLISHED

                    10 ->
                        PAYOUTTXPUBLISHEDMSGSENT

                    11 ->
                        PAYOUTTXPUBLISHEDMSGARRIVED

                    12 ->
                        PAYOUTTXPUBLISHEDMSGINMAILBOX

                    13 ->
                        PAYOUTTXPUBLISHEDMSGSENDFAILED

                    14 ->
                        RECEIVEDPAYOUTTXPUBLISHEDMSG

                    15 ->
                        PAYOUTTXSEENINNETWORK

                    _ ->
                        MediationResultStateUnrecognized_ i
            )


{-| `MediationResultState` enumeration

-}
type MediationResultState
    = PBERRORMEDIATIONRESULT
    | UNDEFINEDMEDIATIONRESULT
    | MEDIATIONRESULTACCEPTED
    | MEDIATIONRESULTREJECTED
    | SIGMSGSENT
    | SIGMSGARRIVED
    | SIGMSGINMAILBOX
    | SIGMSGSENDFAILED
    | RECEIVEDSIGMSG
    | PAYOUTTXPUBLISHED
    | PAYOUTTXPUBLISHEDMSGSENT
    | PAYOUTTXPUBLISHEDMSGARRIVED
    | PAYOUTTXPUBLISHEDMSGINMAILBOX
    | PAYOUTTXPUBLISHEDMSGSENDFAILED
    | RECEIVEDPAYOUTTXPUBLISHEDMSG
    | PAYOUTTXSEENINNETWORK
    | MediationResultStateUnrecognized_ Int
