{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.NetworkEnvelope exposing (Message)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}

import Proto.Io.Haveno.Protobuffer.Internals_


{-| ## Options

### PreliminaryGetDataRequest

### GetDataResponse

### GetUpdatedDataRequest

### GetPeersRequest

### GetPeersResponse

### Ping

### Pong

### OfferAvailabilityRequest

### OfferAvailabilityResponse

### RefreshOfferMessage

### AddDataMessage

### RemoveDataMessage

### RemoveMailboxDataMessage

### CloseConnectionMessage

### PrefixedSealedAndSignedMessage

### PrivateNotificationMessage

### AddPersistableNetworkPayloadMessage

### AckMessage

### BundleOfEnvelopes

### GetInventoryRequest

### GetInventoryResponse

### SignOfferRequest

### SignOfferResponse

### InitTradeRequest

### InitMultisigRequest

### SignContractRequest

### SignContractResponse

### DepositRequest

### DepositResponse

### DepositsConfirmedMessage

### PaymentSentMessage

### PaymentReceivedMessage

### DisputeOpenedMessage

### DisputeClosedMessage

### ChatMessage

### MediatedPayoutTxSignatureMessage

### MediatedPayoutTxPublishedMessage

### FileTransferPart

-}
type alias Message =
    Proto.Io.Haveno.Protobuffer.Internals_.Proto__Io__Haveno__Protobuffer__NetworkEnvelope__Message__Message
