{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.Notifications exposing (sendNotification)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 Notifications
/////////////////////////////////////////////////////////////////////////////////////////


@docs sendNotification

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'SendNotification' sending a `SendNotificationRequest` to get back a `SendNotificationReply`.

 only used for testing


-}
sendNotification :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.SendNotificationRequest Proto.Io.Haveno.Protobuffer.SendNotificationReply
sendNotification =
    Grpc.Internal.Rpc
        { service = "Notifications"
        , package = "io.haveno.protobuffer"
        , rpcName = "SendNotification"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeSendNotificationRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeSendNotificationReply
        }
