{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.Offers exposing (cancelOffer, getMyOffer, getMyOffers, getOffer, getOffers, postOffer)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 Offers
/////////////////////////////////////////////////////////////////////////////////////////


@docs cancelOffer, getMyOffer, getMyOffers, getOffer, getOffers, postOffer

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'CancelOffer' sending a `CancelOfferRequest` to get back a `CancelOfferReply`.

-}
cancelOffer :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.CancelOfferRequest Proto.Io.Haveno.Protobuffer.CancelOfferReply
cancelOffer =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "CancelOffer"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeCancelOfferRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeCancelOfferReply
        }


{-| A template for a gRPC call to the method 'PostOffer' sending a `PostOfferRequest` to get back a `PostOfferReply`.

-}
postOffer : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.PostOfferRequest Proto.Io.Haveno.Protobuffer.PostOfferReply
postOffer =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "PostOffer"
        , encoder = Proto.Io.Haveno.Protobuffer.encodePostOfferRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodePostOfferReply
        }


{-| A template for a gRPC call to the method 'GetMyOffers' sending a `GetMyOffersRequest` to get back a `GetMyOffersReply`.

-}
getMyOffers :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetMyOffersRequest Proto.Io.Haveno.Protobuffer.GetMyOffersReply
getMyOffers =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetMyOffers"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetMyOffersRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetMyOffersReply
        }


{-| A template for a gRPC call to the method 'GetOffers' sending a `GetOffersRequest` to get back a `GetOffersReply`.

-}
getOffers : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetOffersRequest Proto.Io.Haveno.Protobuffer.GetOffersReply
getOffers =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetOffers"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetOffersRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetOffersReply
        }


{-| A template for a gRPC call to the method 'GetMyOffer' sending a `GetMyOfferRequest` to get back a `GetMyOfferReply`.

-}
getMyOffer : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetMyOfferRequest Proto.Io.Haveno.Protobuffer.GetMyOfferReply
getMyOffer =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetMyOffer"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetMyOfferRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetMyOfferReply
        }


{-| A template for a gRPC call to the method 'GetOffer' sending a `GetOfferRequest` to get back a `GetOfferReply`.

-}
getOffer : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetOfferRequest Proto.Io.Haveno.Protobuffer.GetOfferReply
getOffer =
    Grpc.Internal.Rpc
        { service = "Offers"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetOffer"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetOfferRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetOfferReply
        }
