{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.PaymentAccounts exposing (createCryptoCurrencyPaymentAccount, createPaymentAccount, getCryptoCurrencyPaymentMethods, getPaymentAccountForm, getPaymentAccountFormAsJson, getPaymentAccounts, getPaymentMethods, validateFormField)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 PaymentAccounts
/////////////////////////////////////////////////////////////////////////////////////////


@docs createCryptoCurrencyPaymentAccount, createPaymentAccount, getCryptoCurrencyPaymentMethods, getPaymentAccountForm

@docs getPaymentAccountFormAsJson, getPaymentAccounts, getPaymentMethods, validateFormField

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'ValidateFormField' sending a `ValidateFormFieldRequest` to get back a `ValidateFormFieldReply`.

-}
validateFormField :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.ValidateFormFieldRequest Proto.Io.Haveno.Protobuffer.ValidateFormFieldReply
validateFormField =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "ValidateFormField"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeValidateFormFieldRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeValidateFormFieldReply
        }


{-| A template for a gRPC call to the method 'GetCryptoCurrencyPaymentMethods' sending a `GetCryptoCurrencyPaymentMethodsRequest` to get back a `GetCryptoCurrencyPaymentMethodsReply`.

-}
getCryptoCurrencyPaymentMethods :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetCryptoCurrencyPaymentMethodsRequest Proto.Io.Haveno.Protobuffer.GetCryptoCurrencyPaymentMethodsReply
getCryptoCurrencyPaymentMethods =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetCryptoCurrencyPaymentMethods"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetCryptoCurrencyPaymentMethodsRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetCryptoCurrencyPaymentMethodsReply
        }


{-| A template for a gRPC call to the method 'CreateCryptoCurrencyPaymentAccount' sending a `CreateCryptoCurrencyPaymentAccountRequest` to get back a `CreateCryptoCurrencyPaymentAccountReply`.

-}
createCryptoCurrencyPaymentAccount :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.CreateCryptoCurrencyPaymentAccountRequest Proto.Io.Haveno.Protobuffer.CreateCryptoCurrencyPaymentAccountReply
createCryptoCurrencyPaymentAccount =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "CreateCryptoCurrencyPaymentAccount"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeCreateCryptoCurrencyPaymentAccountRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeCreateCryptoCurrencyPaymentAccountReply
        }


{-| A template for a gRPC call to the method 'GetPaymentAccountFormAsJson' sending a `GetPaymentAccountFormAsJsonRequest` to get back a `GetPaymentAccountFormAsJsonReply`.

-}
getPaymentAccountFormAsJson :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetPaymentAccountFormAsJsonRequest Proto.Io.Haveno.Protobuffer.GetPaymentAccountFormAsJsonReply
getPaymentAccountFormAsJson =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetPaymentAccountFormAsJson"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetPaymentAccountFormAsJsonRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetPaymentAccountFormAsJsonReply
        }


{-| A template for a gRPC call to the method 'GetPaymentAccountForm' sending a `GetPaymentAccountFormRequest` to get back a `GetPaymentAccountFormReply`.

-}
getPaymentAccountForm :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetPaymentAccountFormRequest Proto.Io.Haveno.Protobuffer.GetPaymentAccountFormReply
getPaymentAccountForm =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetPaymentAccountForm"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetPaymentAccountFormRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetPaymentAccountFormReply
        }


{-| A template for a gRPC call to the method 'GetPaymentMethods' sending a `GetPaymentMethodsRequest` to get back a `GetPaymentMethodsReply`.

-}
getPaymentMethods :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetPaymentMethodsRequest Proto.Io.Haveno.Protobuffer.GetPaymentMethodsReply
getPaymentMethods =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetPaymentMethods"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetPaymentMethodsRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetPaymentMethodsReply
        }


{-| A template for a gRPC call to the method 'GetPaymentAccounts' sending a `GetPaymentAccountsRequest` to get back a `GetPaymentAccountsReply`.

-}
getPaymentAccounts :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetPaymentAccountsRequest Proto.Io.Haveno.Protobuffer.GetPaymentAccountsReply
getPaymentAccounts =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetPaymentAccounts"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetPaymentAccountsRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetPaymentAccountsReply
        }


{-| A template for a gRPC call to the method 'CreatePaymentAccount' sending a `CreatePaymentAccountRequest` to get back a `CreatePaymentAccountReply`.

-}
createPaymentAccount :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.CreatePaymentAccountRequest Proto.Io.Haveno.Protobuffer.CreatePaymentAccountReply
createPaymentAccount =
    Grpc.Internal.Rpc
        { service = "PaymentAccounts"
        , package = "io.haveno.protobuffer"
        , rpcName = "CreatePaymentAccount"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeCreatePaymentAccountRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeCreatePaymentAccountReply
        }
