{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.PersistableEnvelope exposing (Message)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}

import Proto.Io.Haveno.Protobuffer.Internals_


{-| ## Options

### SequenceNumberMap

### PeerList

### AddressEntryList

### NavigationPath

### TradableList

### ArbitrationDisputeList

### PreferencesPayload

### UserPayload

### PaymentAccountList

### AccountAgeWitnessStore

### SignedWitnessStore

### MediationDisputeList

### RefundDisputeList

### TradeStatistics3Store

### MailboxMessageList

### IgnoredMailboxMap

### RemovedPayloadsMap

### XmrAddressEntryList

### SignedOfferList

### EncryptedConnectionList

-}
type alias Message =
    Proto.Io.Haveno.Protobuffer.Internals_.Proto__Io__Haveno__Protobuffer__PersistableEnvelope__Message__Message
