{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.ShutdownServer exposing (stop)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 Shutdown
/////////////////////////////////////////////////////////////////////////////////////////


@docs stop

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'Stop' sending a `StopRequest` to get back a `StopReply`.

-}
stop : Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.StopRequest Proto.Io.Haveno.Protobuffer.StopReply
stop =
    Grpc.Internal.Rpc
        { service = "ShutdownServer"
        , package = "io.haveno.protobuffer"
        , rpcName = "Stop"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeStopRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeStopReply
        }
