{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.XmrNode exposing (getXmrNodeSettings, isXmrNodeOnline, startXmrNode, stopXmrNode)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `grpc.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

/////////////////////////////////////////////////////////////////////////////////////////
 XmrNode
/////////////////////////////////////////////////////////////////////////////////////////


@docs getXmrNodeSettings, isXmrNodeOnline, startXmrNode, stopXmrNode

-}

import Grpc.Internal
import Proto.Io.Haveno.Protobuffer


{-| A template for a gRPC call to the method 'StopXmrNode' sending a `StopXmrNodeRequest` to get back a `StopXmrNodeReply`.

-}
stopXmrNode :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.StopXmrNodeRequest Proto.Io.Haveno.Protobuffer.StopXmrNodeReply
stopXmrNode =
    Grpc.Internal.Rpc
        { service = "XmrNode"
        , package = "io.haveno.protobuffer"
        , rpcName = "StopXmrNode"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeStopXmrNodeRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeStopXmrNodeReply
        }


{-| A template for a gRPC call to the method 'StartXmrNode' sending a `StartXmrNodeRequest` to get back a `StartXmrNodeReply`.

-}
startXmrNode :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.StartXmrNodeRequest Proto.Io.Haveno.Protobuffer.StartXmrNodeReply
startXmrNode =
    Grpc.Internal.Rpc
        { service = "XmrNode"
        , package = "io.haveno.protobuffer"
        , rpcName = "StartXmrNode"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeStartXmrNodeRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeStartXmrNodeReply
        }


{-| A template for a gRPC call to the method 'GetXmrNodeSettings' sending a `GetXmrNodeSettingsRequest` to get back a `GetXmrNodeSettingsReply`.

-}
getXmrNodeSettings :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.GetXmrNodeSettingsRequest Proto.Io.Haveno.Protobuffer.GetXmrNodeSettingsReply
getXmrNodeSettings =
    Grpc.Internal.Rpc
        { service = "XmrNode"
        , package = "io.haveno.protobuffer"
        , rpcName = "GetXmrNodeSettings"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeGetXmrNodeSettingsRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeGetXmrNodeSettingsReply
        }


{-| A template for a gRPC call to the method 'IsXmrNodeOnline' sending a `IsXmrNodeOnlineRequest` to get back a `IsXmrNodeOnlineReply`.

-}
isXmrNodeOnline :
    Grpc.Internal.Rpc Proto.Io.Haveno.Protobuffer.IsXmrNodeOnlineRequest Proto.Io.Haveno.Protobuffer.IsXmrNodeOnlineReply
isXmrNodeOnline =
    Grpc.Internal.Rpc
        { service = "XmrNode"
        , package = "io.haveno.protobuffer"
        , rpcName = "IsXmrNodeOnline"
        , encoder = Proto.Io.Haveno.Protobuffer.encodeIsXmrNodeOnlineRequest
        , decoder = Proto.Io.Haveno.Protobuffer.decodeIsXmrNodeOnlineReply
        }
