{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Io.Haveno.Protobuffer.IfscBasedAccountPayload.Message exposing (Message(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.3
- `protoc` 3.12.4
- the following specification files: `pb.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Message

-}


{-| ## Options

### NeftAccountPayload

### RtgsAccountPayload

### ImpsAccountPayload

-}
type Message a0 a1 a2
    = NeftAccountPayload a0
    | RtgsAccountPayload a1
    | ImpsAccountPayload a2
